# Generated by Django 2.0.7 on 2018-07-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_personalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalnote',
            name='category',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='personalnote',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personalnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='personalnote',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='personalnote',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
